x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '4.3.7'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  deployerServiceAccount:
    description: >
      Creates app resources, including the MinIO Tenant CRD.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups: ['apiextensions.k8s.io', 'rbac.authorization.k8s.io']
            resources: ['customresourcedefinitions', 'clusterroles', 'clusterrolebindings']
            verbs: ['*']

  # The images property will be filled in during part 2
  images:
    '':
      properties:
        imageRepo: 
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    console:
      properties:
        imageConsoleRepo:
          type: REPO_WITH_REGISTRY
        imageConsoleTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      
required:
- name
- namespace